package oauth2

import "errors"

var (
	ErrInvalidRequest                  = errors.New("invalid request")
	ErrUnsupportedResponseType         = errors.New("unsupported response type")
	ErrInvalidScope                    = errors.New("invalid scope")
	ErrInvalidRedirectURI              = errors.New("invalid redirect uri")
	ErrServerError                     = errors.New("server error")
	ErrLoginRequired                   = errors.New("login required")
	ErrUnauthorizedClient              = errors.New("unauthorized client")
	ErrRedirectURIMismatch             = errors.New("redirect uri mismatch")
	ErrClientNotFound                  = errors.New("client not found")
	ErrClientEmptyOwnerId              = errors.New("client owner id cannot be empty")
	ErrClientEmptyName                 = errors.New("client name cannot be empty")
	ErrClientEmptyDomain               = errors.New("client domain cannot be empty")
	ErrClientEmptyRedirectURI          = errors.New("client redirect URI cannot be empty")
	ErrClientInvalidRedirectURI        = errors.New("client redirect URI is not a valid URL")
	ErrClientRedirectURIDomainMismatch = errors.New("client redirect URI domain does not match client domain")
	ErrUnsupportedGrantType            = errors.New("unsupported grant type")
	ErrInvalidClient                   = errors.New("invalid client")
	ErrInvalidCode                     = errors.New("invalid authorization code")
	ErrCodeExpired                     = errors.New("authorization code expired")
	ErrCodeMismatch                    = errors.New("authorization code mismatch")
	ErrInvalidCodeChallenge            = errors.New("invalid code challenge")
	ErrInvalidCodeChallengeMethod      = errors.New("invalid code challenge method, only S256 is supported")
	ErrInvalidCodeVerifier             = errors.New("invalid code verifier")
	ErrMissingCodeVerifier             = errors.New("code verifier is required for PKCE authorization code")
	ErrInvalidToken                    = errors.New("invalid token")
	ErrInsufficientScope               = errors.New("insufficient scope")
	ErrInvalidClientType               = errors.New("invalid client type")
	ErrPKCERequired                    = errors.New("PKCE is required for public clients")
	ErrClientOwnerMismatch             = errors.New("client owner mismatch")
)
